application: vanlangtechvn
version: 2
runtime: python
api_version: 1

default_expiration: "1d"

handlers:
  - url: /favicon.ico
    static_files: static/themes/vanlang/images/vanlang/favicon2.ico
    upload: static/themes/vanlang/images/vanlang/favicon2.ico

  - url: /static/images/fileicons/.*
    script: zip_handler.py
    
  - url: /fckeditor/.*
    script: zip_handler.py
  
  - url: /static
    static_dir: static
 
  - url: /admin/.*
    script: main.py
    login: required
 
  - url: /.*
    script: main.py
    

    
skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (dev/.*)|
 (tests/.*)|
 (docs/.*)|
 )$